// This snippet file was generated by processing the source file:
// ./auth-next/google-signin.js
//
// To update the snippets in this file, edit the source and then run
// 'npm run snippets'.

// [START auth_google_signin_popup_modular]
import { getAuth, signInWithPopup, signOut, GoogleAuthProvider } from "firebase/auth";
// import { GoogleAuthProvider } from "firebase/auth"

function signOutElf() {
    const auth = getAuth();
    signOut(auth).then(() => {
        console.log("Sign-out successful.");
    }).catch((error) => {
        console.log("Sign-out An error happened.");
    });
}

function signIn() {
    const provider = new GoogleAuthProvider();
    const auth = getAuth();
    signInWithPopup(auth, provider)
        .then((result) => {
            console.log("Sign-in successful.");
            // This gives you a Google Access Token. You can use it to access the Google API.
            const credential = GoogleAuthProvider.credentialFromResult(result);
            const token = credential.accessToken;
            // The signed-in user info.
            const user = result.user;
            // ...
        }).catch((error) => {
            // Handle Errors here.
            console.log("Sign-in, an error happened.");
            const errorCode = error.code;
            const errorMessage = error.message;
            // The email of the user's account used.
            const email = error.customData.email;
            // The AuthCredential type that was used.
            const credential = GoogleAuthProvider.credentialFromError(error);
            // ...
        });

}

export { signIn, signOutElf };