/* This snippet file was generated by processing the source file:
./firestore-next/test.firestore.js

To update the snippets in this file, edit the source and then run
'npm run snippets'. 

https://github.com/firebase/snippets-web

git clone git@github.com:firebase/snippets-web.git

https://github.com/firebase/snippets-web/blob/36740fb2c39383621c0c0a948236e9eab8a71516/snippets/firestore-next/test-firestore/set_with_merge.js#L8-L11
*/

// [START set_with_merge_modular]
import { doc, setDoc } from "firebase/firestore";

const cityRef = doc(db, 'cities', 'BJ');
setDoc(cityRef, { capital: true }, { merge: true });
// [END set_with_merge_modular]